### ISSUE TITLE
Broken app catalog entry

### ISSUE THREAD

**Issue by MichaelGrafnetter** [anakod/flipper_passgen#7]
Hello, I am unable to find the Password Generator app in the app catalog through the iOS Flipper app, even though the [manifest is present](https://github.com/flipperdevices/flipper-application-catalog/blob/9e9fbb2b4cacb829f68c308fae64b44e25fd1eee/applications/Tools/passgen/manifest.yml) in the official repo. I presume that flipper_passgen manifest/repo probably is not fully compatible with their automated build system.
I also noticed that they are sourcing the app from the [xMasterX/all-the-plugins](https://github.com/xMasterX/all-the-plugins/tree/main/apps_source_code/flipper_passgen) repo instead of [anakod/flipper_passgen](https://github.com/anakod/flipper_passgen).

**Comment by henrygab** [comment]
Looks like the xMasterX source manually pulled these latest changes to remove bias / clarify TRNG use.

~~That was only a couple days ago.  Could it just need a few days to work through the pipelines??~~

The manifest points to commit SHA of [1606da9d9f0dbdc239387c9fb061bb25b4e94720](https://github.com/xMasterX/all-the-plugins/commit/1606da9d9f0dbdc239387c9fb061bb25b4e94720).

Perhaps that simply needs to be updated to point to commit SHA of [6647fb0222a3a27fb5773f3153c78a85ba885054](https://github.com/xMasterX/all-the-plugins/commit/6647fb0222a3a27fb5773f3153c78a85ba885054)?  I went ahead and created a [PR in the official repo](https://github.com/flipperdevices/flipper-application-catalog/pull/88) to update that hash.  We'll see how that goes.....

**Comment by henrygab** [comment]
I've updated the official app list to point to the new commit SHA.  The PR was approved, so ... should show up relatively soon.

**Comment by MichaelGrafnetter** [comment]
Great, it's already [published in the catalog](https://lab.flipper.net/apps/passgen).
